# Session Store Configuration
# ===========================
# Este archivo es la fuente única de verdad para la configuración del session-store.
# Todas las configuraciones deben definirse aquí, no mediante variables de entorno.

# Configuración del servidor HTTP
[server]
port = 8080
# Entorno de ejecución (development, production)
node_env = "production"

# Configuración de la base de datos PostgreSQL
[database]
# URL de conexión a PostgreSQL
# Formato: postgres://usuario:password@host:puerto/database
url = "postgres://postgres:postgres@postgres:5432/session_store"

# Configuración de MediaMTX (servidor de playback)
[mediamtx]
# URL base del API de playback de MediaMTX
playback_base_url = "http://mediamtx:9996"

# Configuración de playback de grabaciones
[playback]
# Segundos extra agregados al final de la grabación
extra_seconds = 1
# Offset de inicio en milisegundos (para compensar latencia)
start_offset_ms = 1500

# Configuración de frames (imágenes de detecciones)
[frames]
# Directorio donde se guardan los frames con detecciones
storage_path = "/data/frames"
