# ===========================
# Session Store Configuration
# ===========================

# Configuración del servidor HTTP
[server]
port = 8080
# Entorno de ejecución (development, production)
node_env = "production"

# Configuración de la base de datos PostgreSQL
[database]
# URL de conexión a PostgreSQL
# Formato: postgres://usuario:password@host:puerto/database
url = "postgres://postgres:postgres@postgres:5432/session_store"

# Configuración de MediaMTX (servidor de playback)
[mediamtx]
# URL base del API de playback de MediaMTX
playback_base_url = "http://mediamtx:9996"
# Duración de segmentos de grabación en segundos (debe coincidir con recordSegmentDuration)
segment_duration_sec = 300
# Token opcional para validar hooks (dejar vacío para desactivar)
# hook_token = "your-secret-token"

# Configuración de playback de grabaciones
[playback]
# Segundos extra agregados al final de la grabación
extra_seconds = 1
# Offset de inicio en milisegundos (fallback cuando media_start_ts no está disponible)
start_offset_ms = 1000

# Configuración de frames (imágenes de detecciones)
[frames]
# Directorio donde se guardan los frames con detecciones
storage_path = "/data/frames"

# Configuración de tracks persistidos por el worker
[tracks]
# Directorio base que contiene meta/index y segmentos NDJSON por sesión
storage_path = "/data/tracks"
