# Web UI Configuration
# =====================
# Este archivo es la fuente única de verdad para la configuración del web-ui.
# Todas las configuraciones deben definirse aquí, no mediante variables de entorno.

# Configuración del servidor HTTP
[server]
# Puerto de escucha del servidor web
port = 3000

# Configuración del backend (Session Store)
[backend]
# URL del servicio session-store
session_store_url = "http://session-store:8080"
# URL del servicio MediaMTX (para proxy de playback)
mediamtx_url = "http://mediamtx:9996"
